# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0002_auto_20160731_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_url', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlexpander.URL')),
            ],
        ),
    ]
