# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0003_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='website_img',
            field=models.ImageField(default='image_not_available.jpg', upload_to='images'),
        ),
    ]
