# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0004_url_website_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='website_img',
            field=models.ImageField(default='image_not_available.jpg', upload_to='jhall38-lab3'),
        ),
    ]
