# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0005_auto_20160818_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='archived',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='urlexpander.Archived'),
        ),
        migrations.AlterField(
            model_name='url',
            name='website_img',
            field=models.ImageField(default='image_not_available.jpg', upload_to='images'),
        ),
    ]
